# version: "3.8"
services:
  nodesupabase:
    image: supabaseinsert:latest
    container_name: nodesupabase
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_PORT: 5000
      NODE_PALWORLD_APUURL: http://10.148.0.3:8212/v1/api/
      NODE_RCON_PORT: 25575
      NODE_RCON_USER: admin
      NODE_RCON_PASSWORD: password
      DATABASE_URL: postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public
    depends_on:
      - palworld

  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
      - 25575:25575/tcp
      - 8212:8212/tcp
    env_file:
      - .env
    volumes:
      - ./palworld:/palworld/
